#%RAML 1.0
title: craftsoft-customer-sys-proc-API

/customer:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                
              }
  /{customerId}:
/invalidCustomer:
  /{InvalidCustomerId}:
