#%RAML 1.0
title: craftsoft-customer-sys-proc-API
types:
  customerDataType: !include DataType/customerDataType.raml
resourceTypes:
  customerResourceType: !include ResourceType/customerResourceType.raml
traits:
  errorResponse: !include trait.raml
securitySchemes:
  ba



/customer:
  type:
    customerResourceType:
        examplereference:
                !include Examples/customerExample.raml
    is:
      - errorResponse
      
  