#%RAML 1.0
title: craftsoft-customer-sys-proc-API
uses:
  
/customer:
  type:
    customerResourceType:
        examplereference:
                !include Examples/customerExample.raml
    is:
      - errorResponse
      
  