#%RAML 1.0 SecurityScheme
type: OAuth 2.0 
describedBy:
    headers:
      client_id:
        type: string
        example: xyz
        required: true
      client_secret:
        type: string
        example: xyz
        required: true