#%RAML 1.0 SecurityScheme
type: basic
describedBy:
    headers:
      client_id:
        type: string
        example: xyz
        required: true
      client_secret:
        type: string
        example: xyz
        required: true