#%RAML 1.0 NamedExample
  [{
                tags : "teamB",
	              telephoneNumber : '+16788652215',
	              customerID : '6954453238077',
	              id_hr : '43',
	              zipCode : '10012',
	              fullName : 'AdilAhmed',
	              email : 'adil.ahmed@microsoft.com',
	              latitude : '40.7256',
	              longitude : '-73.9982',
	              temp_min : '280.86',
	              temp_max : 289.5,
	              muleTimestamp : '2023-04-01 03:11:11'
              },
              {
                tags : "teamB",
	              telephoneNumber : '+16788652215',
	              customerID : '6954453238077',
	              id_hr : 43,
	              zipCode : '10012',
	              fullName : 'AdilAhmed',
	              email : 'adil.ahmed@microsoft.com',
	              latitude : '40.7256',
	              longitude : '-73.9982',
	              temp_min : '280.86',
	              temp_max : 289.5,
	              muleTimestamp : '2023-04-01 03:11:11'
              }]