#%RAML 1.0 NamedExample
 [{
                tags : 'Team_D',
	              telephoneNumber : '+14256970933',
	              customerID : '6954453303613',
	              id_hr: '34',
	              zipCode : '60654',
	              fullName : 'Binyam B',
	              email : 'binyam.b@gmail.com',
	              muleTimestamp : '2023-04-02 00:26:00.804147'
              },{
                tags : 'Team_D',
	              telephoneNumber : '+14256970933',
	              customerID : '6954453303613',
	              id_hr: '34',
	              zipCode : '60654',
	              fullName : 'Binyam B',
	              email : 'binyam.b@gmail.com',
	              muleTimestamp : '2023-04-02 00:26:00.804147'
              }]