#%RAML 1.0 DataType
type: object
properties:
  tags : string
  telephoneNumber : string
  customerID : string
  id_hr : integer
  zipCode : string
  fullName : string
  email : string
  latitude : number
  longitude : number
  temp_min : number
  temp_max : number
  muleTimestamp : string